/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-QyMzJ-RLMJtC3gYsxvcLAGPWFgq015Rb38s0P-CDq2IG0rLC44zO73h0mbERf1PeZrRihPu79LvS7G-djS8BtCppo3fNyIzFKB59g5vxZ-ZhRP-DWpK7yLRl",
  "tt": "tt-1-HdqOa-xMxZ5EM7bB88t384ZI-aMo-ZPmqNtUw6sBFg8=",
  "version": "2020-11-20"
}

export default ebconfig;